In [1]:
import pandas as pd
import json
df = pd.read_html('https://en.wikipedia.org/wiki/Demographics_of_India', header=0)[8]
fortune_500 = json.loads(df.to_json(orient="records"))
df

,Rank,State/UT,Population[59],Percent (%),Male,Female,Difference between male and female,Sex ratio,Rural[60],Urban[60],Area[61] (km2),Density (per km2)
0,1,Uttar Pradesh,199812341,16.50,104480510,95331831,9148679,930,155111022,44470455,240928,828
1,2,Maharashtra,112374333,9.28,58243056,54131277,4111779,929,61545441,50827531,307713,365
2,3,Bihar,104099452,8.60,54278157,49821295,4456862,918,92075028,11729609,94163,1102
3,4,West Bengal,91276115,7.54,46809027,44467088,2341939,950,62213676,29134060,88752,1030
4,5,Madhya Pradesh,72626809,6.00,37612306,35014503,2597803,931,52537899,20059666,308245,236
5,6,Tamil Nadu,72147030,5.96,36137975,36009055,128920,996,37189229,34949729,130058,555
6,7,Rajasthan,68548437,5.66,35550997,32997440,2553557,928,51540236,17080776,342239,201
7,8,Karnataka,61095297,5.05,30966657,30128640,838017,973,37552529,23578175,191791,319
8,9,Gujarat,60439692,4.99,31491260,28948432,2542828,919,34670817,25712811,196024,308
9,10,Andhra Pradesh,49386799,4.08,24738068,24648731,89337,996,34776389,14610410,160205,308
10,11,Odisha,41974218,3.47,21212136,20762082,450054,979,34951234,6996124,155707,269
11,12,Telangana,35193978,2.91,17704078,17489900,214178,988,21585313,13608665,114840,307
12,13,Kerala,33406061,2.76,16027412,17378649,-1351237,1084,17445506,15932171,38863,859
13,14,Jharkhand,32988134,2.72,16930315,16057819,872496,948,25036946,7929292,79714,414
14,15,Assam,31205576,2.58,15939443,15266133,673310,958,26780526,4388756,78438,397
15,16,Punjab,27743338,2.29,14639465,13103873,1535592,895,17316800,10387436,50362,550
16,17,Chhattisgarh,25545198,2.11,12832895,12712303,120592,991,19603658,5936538,135191,189
17,18,Haryana,25351462,2.09,13494734,11856728,1638006,879,16531493,8821588,44212,573
18,19,Delhi (UT),16787941,1.39,8887326,7800615,1086711,868,944727,12905780,1484,11297
19,20,Jammu and Kashmir,12541302,1.04,6640662,5900640,740022,889,9134820,3414106,222236,56
20,21,Uttarakhand,10086292,0.83,5137773,4948519,189254,963,7025583,3091169,53483,189
21,22,Himachal Pradesh,6864602,0.57,3481873,3382729,99144,972,6167805,688704,55673,123
22,23,Tripura,3673917,0.30,1874376,1799541,74835,960,2710051,960981,10486,350
23,24,Meghalaya,2966889,0.25,1491832,1475057,16775,989,2368971,595036,22429,132
24,25,Manipur,2855794,0.24,1438687,1417107,21580,985,1899624,822132,22327,128
25,26,Nagaland,1978502,0.16,1024649,953853,70796,931,1406861,573741,16579,119
26,27,Goa,1458545,0.12,739140,719405,19735,973,551414,906309,3702,394
27,28,Arunachal Pradesh,1383727,0.11,713912,669815,44097,938,1069165,313446,83743,17
28,29,Puducherry (UT),1247953,0.10,612511,635442,-22931,1037,394341,850123,479,2598
29,30,Mizoram,1097206,0.09,555339,541867,13472,976,529037,561997,21081,52
30,31,Chandigarh (UT),1055450,0.09,580663,474787,105876,818,29004,1025682,114,9252
31,32,Sikkim,610577,0.05,323070,287507,35563,890,455962,151726,7096,86
32,33,Andaman and Nicobar Islands (UT),380581,0.03,202871,177710,25161,876,244411,135533,8249,46
33,34,Dadra and Nagar Haveli (UT),343709,0.03,193760,149949,43811,774,183024,159829,491,698
34,35,Daman and Diu (UT),243247,0.02,150301,92946,57355,618,60331,182580,112,2169
35,36,Lakshadweep (UT),64473,0.01,33123,31350,1773,946,14121,50308,32,2013
36,–,Total (India),1210854977,100.00,623724248,586469174,35585741,943,833087662,377105760,3287240,382

In [2]:
df.to_csv("population.csv")